name: UV Run Pytest
run-name: ${{ github.actor }} is running Pytest with UV
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true
            python-version: "3.10"
        
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run Pytest 
        run: uv run pytest tests/